server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:lb://PRODUCT-SERVICE}
          predicates:
            - Path=${PRODUCT_SERVICE_PATH:/product-service/**}
          filters:
            - RewritePath=${PRODUCT_SERVICE_PATH:/product-service/(?<path>.*)}, /$\{path}
        - id: order-service
          uri: ${ORDER_SERVICE_URL:lb://ORDER-SERVICE}
          predicates:
            - Path=${ORDER_SERVICE_PATH:/order-service/**}
          filters:
            - RewritePath=${ORDER_SERVICE_PATH:/order-service/(?<path>.*)}, /$\{path}
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:lb://INVENTORY-SERVICE}
          predicates:
            - Path=${INVENTORY_SERVICE_PATH:/inventory-service/**}
          filters:
            - RewritePath=${INVENTORY_SERVICE_PATH:/inventory-service/(?<path>.*)}, /$\{path}
        - id: cart-service
          uri: ${CART_SERVICE_URL:lb://CART-SERVICE}
          predicates:
            - Path=${CART_SERVICE_PATH:/cart-service/**}
          filters:
            - RewritePath=${CART_SERVICE_PATH:/cart-service/(?<path>.*)}, /$\{path}\

        - id: discovery-server-static
          uri: ${DISCOVERY_SERVICE_URL:http://discovery-server:8761}
          predicates:
            - Path=${DISCOVERY_SERVICE_PATH:/eureka/**}
          filters:
            - SetPath=${DISCOVERY_SERVICE_PATH:/}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka